<html><head>
    <title>Alive - Apperciate Love In Volunteering Everyday</title>    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">  <link rel="stylesheet" href="homepage.css">  <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>  <script>$('.dropdown-toggle').dropdown()</script>	</head>
	<body>
	  <div id="header">    <div id="navbar" class="row">      <div class="col-md-3 bar">        <h1>Alive</h1>      </div>      <div class="collapse navbar-collapse">        <ul class="nav navbar-nav">          <div class="btn-group">            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">              Start Volunteering            </button>            </div>          </ul></div>          <div class="btn-group">            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">              Search Organization            </button>            </div>          <div class="btn-group">            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">              Post a job            </button>            </div>          <div class="btn-group" role="group">            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">              Find a job            </button>            </div>                <ul class="nav navbar-nav">          <li><a href="#">About us</a></li>        </ul>        <div class"col-md-1"="">          <button class="btn btn-default" type="button">Login</button>          <button class="btn btn-default" type="button">Register</button>        </div>          <!---search box--->        <div class="input-group col-md-4">          <input type="text" class="form-control" placeholder="Keywords">        </div>        <div class="input-group col-md-4">          <input type="text" class="form-control" placeholder="Location">          <span class="input-group-btn">            <button class="btn btn-default" type="button">Search</button>          </span>        </div>      <!---search box--->    </div>  </div>    <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4">
    </div>
  </div>
        <div id="footer" class="row">        <div class="About col-md-3">          <h3>About</h3>          <p>About us</p>          <p>Privacy Policy</p>          <p>Customer Service</p>        </div>        <div class="Help col-md-3">          <h3>Help</h3>          <p>Help Center</p>          <p>Get Started</p>          <p>Contact us</p>        </div>        <div class="Visit-us col-md-3">          <h3>Follow Us</h3>            <img src="images/facebookicon.png" height="30px" weight="30px">            <img src="images/twitter-128.png" height="30px" weight="30px">            <img src="images/google-plus-flat.png" height="30px" weight="30px">        </div>        <div class="Contact col-md-3">          <p>Stay Connected</p>          <div class="input-group">              <input type="text" class="form-control" placeholder="Email Address">              <span class="input-group-btn">                <button class="btn btn-default" type="button">Submit</button>              </span>          </div>        </div>      </div>  

</body></html>